---
project:
  title: Meteo Maps
  description: "API for geo-data on a map"
  version: "0.6.1"
  rapydo: "3.0"

variables:
  env:
    ACTIVATE_AUTH: 0
    FRONTEND_FRAMEWORK: nofrontend
    CORS_ALLOWED_ORIGIN: "*"
    SET_MAX_REQUESTS_PER_SECOND_API: 999999
    PLATFORM: G100
    DATA_PATH: /meteo
    ALLOWED_IPS: {}
