---
project:
  title: Meteo Maps
  description: "API for geo-data on a map"
  version: "0.6.1"
  rapydo: "3.0"

variables:
  env:
    ACTIVATE_AUTH: 0
    ACTIVATE_REDIS: 1
    ACTIVATE_CELERY: 1
    ACTIVATE_CELERYBEAT: 1
    CELERY_ENABLE_CONNECTOR: 1
    CELERY_BROKER: REDIS
    CELERY_BACKEND: REDIS
    FRONTEND_FRAMEWORK: nofrontend
    CORS_ALLOWED_ORIGIN: "*"
    SET_MAX_REQUESTS_PER_SECOND_API: 999999
    PLATFORM: G100
    DATA_PATH: /meteo
    GEOTIFF_DIR: ${DATA_DIR}/maps
    ALLOWED_IPS: {}
